branch-defaults:
  main:
    environment: reminder-app-prod
    group_suffix: null
  develop:
    environment: reminder-app-dev
    group_suffix: null

global:
  application_name: reminder-app
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application 